name: Publish docs to Wiki

on:
  push:
    branches: [main]
    paths:
      - wiki/**

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository source
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki-repo

      - name: Sync wiki files
        run: |
          rsync -av --delete repo/wiki/ wiki-repo/
          cd wiki-repo
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update wiki from repo"
            git push
          else
            echo "No wiki changes to commit"
          fi
