---
name: Publish docs to Wiki

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
    paths:
      - wiki/**
  push:
    branches: [main]
    paths:
      - wiki/**

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync wiki
        uses: newrelic/wiki-sync-action@v1
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.GITHUB_TOKEN }}
